title: 'Txt by HTML5 UP'
author:
  name: Hugh Barnes
  # email: 'joe@test.com'
metadata:
    description: 'Demo of port of HTML5UP Txt theme to Grav content management system.'
    about: |
      <p>
      This is <strong>TXT</strong>, yet another free responsive site template designed by	<a href="http://twitter.com/ajlkn">AJ</a> for <a href="http://html5up.net">HTML5 UP</a>. It's released under the <a href="http://html5up.net/license/">Creative Commons Attribution</a> license so feel free to use it for whatever you're working on (personal or commercial), just be sure to give us credit for the design.	That's basically it :)
      </p>
    rights: © Untitled. All rights reserved

globals:

  # contacts:
  #   email: info@example.com
  #   phone:
  #     - '(+1) 000 123 456789'
  #     - '+2 987 654 321'
  #   address: 'Eiusmod Tempor inc ,St Dolore Place,Kingsport 56777' # optional in template

  social: # these names are added to make the social links show
    facebook: vacuousExample
    twitter: realDonaldExample
    instagram: selfieExample
    dribbble: drabExample
    linkedin: porfesionalExample
